### ISSUE TITLE
The name of the user should be displayed in the header besides the image

### ISSUE THREAD

**Issue by Valenie** [ajency/Giftology#17]
![image](https://cloud.githubusercontent.com/assets/19943710/24184217/ea746d76-0ef2-11e7-8559-cbc714229ae0.png)

**Comment by antoniojfurtado** [comment]
@ajajrajguru Need HTML for this

**Comment by ajajrajguru** [comment]
@Valenie Added username in dropdown not besides the image as name can consume lot of space and also there will be an action besides it so its better to add it in dropdown.
@antoniojfurtado Added username in dropdown please pass data to it.
Thanks.

**Comment by Valenie** [comment]
Retested and fixed.
