### ISSUE TITLE
There is no resend email action for invitees that havent contributed

### ISSUE THREAD

**Issue by Valenie** [ajency/Giftology#20]

**Comment by antoniojfurtado** [comment]
@ajajrajguru Need HTML for this

**Comment by ajajrajguru** [comment]
Provided with Html.

**Comment by antoniojfurtado** [comment]
@Valenie Should this action always send an email or there should be an interval between resends?

**Comment by Valenie** [comment]
@antoniojfurtado it should always resend emails.
