### ISSUE TITLE
When the user enters multiple email addresses to invite contributors only some get saved.

### ISSUE THREAD

**Issue by Valenie** [ajency/Giftology#21]
1) Add multiple emails
2) Click on save
3) Only some are displayed
4) Click back , only some emails are displayed and not all

**Comment by antoniojfurtado** [comment]
Can you provide the list of emails you used? There is some regex validation, I need to check if those emails pass my regex.

**Comment by Valenie** [comment]
@antoniojfurtado 

![image](https://cloud.githubusercontent.com/assets/19943710/24190585/120739ce-0f0f-11e7-8e0d-20dca95cd20d.png)

Only the first one got added.

**Comment by Valenie** [comment]
Retested and fixed.
