### ISSUE TITLE
When the invitee adds more invitees, the new invitees should be reflected for all the users

### ISSUE THREAD

**Issue by Valenie** [ajency/Giftology#26]
![image](https://cloud.githubusercontent.com/assets/19943710/24190319/62d58320-0f0e-11e7-8412-3b5d31389be6.png)

![image](https://cloud.githubusercontent.com/assets/19943710/24190342/71c2799c-0f0e-11e7-97f4-0680b3c3848d.png)

**Comment by antoniojfurtado** [comment]
Currently the logic is, I can see only who I have invited, this is a setting(config argument) in code. Can change it to show all invitations regardless of who had sent the invitation.

Had kept it to test out the visibility logic around invites. Will change it to whats required in the next push

**Comment by Valenie** [comment]
Retested and fixed.
