### ISSUE TITLE
When the description has images its not displayed properly

### ISSUE THREAD

**Issue by Valenie** [ajency/Giftology#35]
The riskometer image is right aligned in the backend but not displayed properly,

The side bar description section the image should be adjusted properly irrespective of the size.

![image](https://cloud.githubusercontent.com/assets/19943710/24235067/7a2b73fa-0fc1-11e7-9387-2bd531417ec7.png)

**Comment by ajajrajguru** [comment]
@antoniojfurtado can you please check if the content added is properly generated in their respective grids. Thanks.
