### ISSUE TITLE
MOBILE | The Single view of fund page on mobile should display the image, bucket and description sectio first and then the side bar description

### ISSUE THREAD

**Issue by Valenie** [ajency/Giftology#36]
![image](https://cloud.githubusercontent.com/assets/19943710/24235331/c7df86e4-0fc2-11e7-8732-dfbc532efa3a.png)

**Comment by Valenie** [comment]
@ajajrajguru 
Alignment of term field.
![image](https://cloud.githubusercontent.com/assets/19943710/24442494/08611364-147c-11e7-8bf7-484e8605b774.png)

This does not occupy the full screen.
![image](https://cloud.githubusercontent.com/assets/19943710/24442521/2991691c-147c-11e7-92f3-e953caa567ec.png)

**Comment by ajajrajguru** [comment]
@Valenie text-alignment fixed, regarding second screenshot data entered is not the valid format cannot be a continues words without spaces. Add proper format and check.
