### ISSUE TITLE
The "resend email" action should not be present while sending invites on the invite confirmation pop up

### ISSUE THREAD

**Issue by Valenie** [ajency/Giftology#43]
![image](https://cloud.githubusercontent.com/assets/19943710/24342531/1c2a1e84-12df-11e7-9a12-a10b44574b8d.png)

**Comment by antoniojfurtado** [comment]
This logic is not pushed yet, only the HTML with no logic, please test this later : https://github.com/ajency/Giftology/issues/20

Original Issue is still opened :)
