### ISSUE TITLE
When mandatory fields are not filled while creating a fund, the message should not be post published.

### ISSUE THREAD

**Issue by Valenie** [ajency/Giftology#6]
![image](https://cloud.githubusercontent.com/assets/19943710/23694813/e8b838f6-0401-11e7-9734-3f87b044290a.png)

**Comment by antoniojfurtado** [comment]
This behaviour cannot be suppressed easily,  the post gets published first based on what wordpress deems as valid, only then I can hook into the save operation and validate and save the meta(additional fields) which we define. In case Its not valid I save to draft. But the post published message has already been sent to the UI by then.
