### ISSUE TITLE
Alignment issues and text changes on create a gift page

### ISSUE THREAD

**Issue by Valenie** [ajency/Giftology#88]
![image](https://cloud.githubusercontent.com/assets/19943710/24488460/9888d130-1534-11e7-8d6c-a3d5764a4df7.png)

Text should be "Sarvesh will see this once the gift is received"
Text " No I don't"
![image](https://cloud.githubusercontent.com/assets/19943710/24488628/c2ff49d4-1535-11e7-8713-4b4cc06cced9.png)

![image](https://cloud.githubusercontent.com/assets/19943710/24488664/10b96bd2-1536-11e7-87e8-f81976c9b0be.png)

Template should be "message"
![image](https://cloud.githubusercontent.com/assets/19943710/24488733/8f2c38f0-1536-11e7-969d-9a1ce7622215.png)

**Comment by Valenie** [comment]
@ajajrajguru 
Remove the description for fund.

**Comment by Valenie** [comment]
@ajajrajguru 

![image](https://cloud.githubusercontent.com/assets/19943710/24537258/98d2f376-15fe-11e7-9f59-76d3da36baf3.png)

**Comment by ajajrajguru** [comment]
@Valenie max-height is set for data inside box which is calculated based on one line data of age group,occasion and term, if more than a line for any of those more link will show up as it can be any number of lines for those options.

**Comment by ajajrajguru** [comment]
And data is not getting cut but its the effect for more.
