### ISSUE TITLE
Mozilla | Radio buttons are small and colour on sleection not proper

### ISSUE THREAD

**Issue by Valenie** [ajency/Giftology#91]
![image](https://cloud.githubusercontent.com/assets/19943710/24489109/1f3cf086-1539-11e7-87de-9066da6be233.png)

**Comment by ajajrajguru** [comment]
@Valenie Mozilla doesn't support use of pseudo classes(:after,:before) for form elements(input) which makes it to fallback to default browser version and this can vary as per OS. Solution is to target top parent element which requires maintaining two different browser styles which is not efficient and introducing js for it to work, and not to forget beloved IE :)

Screenshot of **MAC** version

![screen shot 2017-03-30 at 12 54 28 pm](https://cloud.githubusercontent.com/assets/15607085/24492176/13948f46-1548-11e7-958d-a21cb33f901e.png)
