### ISSUE TITLE
Mobile | Alignment issues

### ISSUE THREAD

**Issue by Valenie** [ajency/Giftology#93]
![image](https://cloud.githubusercontent.com/assets/19943710/24489519/96c9c10e-153b-11e7-976e-79538512a22d.png)

![image](https://cloud.githubusercontent.com/assets/19943710/24489575/f080c580-153b-11e7-833c-e37b7e1c25a5.png)

![image](https://cloud.githubusercontent.com/assets/19943710/24489673/739d1ebe-153c-11e7-8a77-d298d8334b31.png)

![image](https://cloud.githubusercontent.com/assets/19943710/24489719/b0f5842c-153c-11e7-983b-73ef2a5a3e37.png)

**Comment by Valenie** [comment]
@ajajrajguru 
![image](https://cloud.githubusercontent.com/assets/19943710/24537056/2684c5fc-15fd-11e7-944c-cbdea4ef603e.png)

![image](https://cloud.githubusercontent.com/assets/19943710/24537090/55d5cfea-15fd-11e7-8130-bb17e1bfe45d.png)

![image](https://cloud.githubusercontent.com/assets/19943710/24537120/96cc0a28-15fd-11e7-9255-aea1dab62298.png)

![image](https://cloud.githubusercontent.com/assets/19943710/24537164/efeb047e-15fd-11e7-9af2-3f09fabbfc39.png)

**Comment by ajajrajguru** [comment]
Left aligned top card data + space issues resolved. Fund card has box-shadow effect to indicate more link.
